name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .npmrc file
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          registry-url: "https://registry.npmjs.org"
      - name: Install npm@latest
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm install --no-fund --no-audit
      - name: Build
        run: npm run build
      - name: Pack
        run: npm pack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
